### ISSUE TITLE
No docker-compose for production?

### ISSUE THREAD

**Issue by socketwiz** [auxilincom/docker-compose-starter#2]
You provided docker-compose.yml in the root that builds the Dockerfile.dev images.  Do you not have a compose file that builds the Dockerfile images for production or am I missing something here?

Also, the link to the blog post in the README is missing, it only has https://.

**Comment by anorsich** [comment]
@socketwiz Great question! 

No, we do not use `docker-compose` for production, just for development. Production workflow looks different: 

Github commit to production branch -> CI test/build/push containers -> CI run [Ansible](https://www.ansible.com/) script to run changed containers on production. 

I am also curious if someone uses `docker-compose` to run containers in a production environment. Could be handy for the small application deployment. 

Let's see if some of our readers going to share this with us.
